//Tim Blythman
#include "io.h"

void ioinit(void){
    ANSELA=63;        //default to analog to disable digital IO buffers
    TRISA=63;        //all inputs for now
}

void setLED(unsigned char n){       //IO maps below generated by a spreadsheet...
    ANSELA=63;      //disable buffers if not needed
    TRISA=63;      //all inputs
    switch(n){
        //below mapping was intended to simplify Tree operation, but still used for other Ornaments
        case  1: LATA=32;TRISA=29;ANSELA=29;break;//LED1
        case  2: LATA= 4;TRISA=57;ANSELA=57;break;//LED2
        case  4: LATA=16;TRISA=45;ANSELA=45;break;//LED3
        case 12: LATA= 2;TRISA=29;ANSELA=29;break;//LED4
        case 10: LATA= 4;TRISA=27;ANSELA=27;break;//LED5
        case  9: LATA=16;TRISA=15;ANSELA=15;break;//LED6
        case  7: LATA= 2;TRISA=57;ANSELA=57;break;//LED7
        case  3: LATA=32;TRISA=27;ANSELA=27;break;//LED8
        case  5: LATA=16;TRISA=43;ANSELA=43;break;//LED9
        case  8: LATA= 2;TRISA=45;ANSELA=45;break;//LED10
        case  6: LATA=32;TRISA=15;ANSELA=15;break;//LED11
        case 11: LATA= 4;TRISA=43;ANSELA=43;break;//LED12
    }
}   
