//Tim Blythman
#include "io.h"

#define ANSEL ANSELA
#define TRISIO TRISA
#define GPIO LATA

void ioinit(void){
    ANSEL=0xF;        //default to analog to disable digital IO buffers
    TRISIO=63;        //all inputs for now
}

void setLED(unsigned char n){       //IO maps below generated by a spreadsheet...
    ANSEL=0xF;      //disable buffers if not needed
    TRISIO=63;      //all inputs
    switch(n){
        case 1: GPIO=32;TRISIO=29;ANSEL=13;break; //LED1
        case 2: GPIO=4;TRISIO=57;ANSEL=9;break; //LED2
        case 4: GPIO=16;TRISIO=45;ANSEL=5;break; //LED3
        case 12: GPIO=2;TRISIO=29;ANSEL=13;break; //LED4
        case 10: GPIO=4;TRISIO=27;ANSEL=11;break; //LED5
        case 9: GPIO=16;TRISIO=15;ANSEL=7;break; //LED6
        case 7: GPIO=2;TRISIO=57;ANSEL=9;break; //LED7
        case 3: GPIO=32;TRISIO=27;ANSEL=11;break; //LED8
        case 5: GPIO=16;TRISIO=43;ANSEL=3;break; //LED9
        case 8: GPIO=2;TRISIO=45;ANSEL=5;break; //LED10
        case 6: GPIO=32;TRISIO=15;ANSEL=7;break; //LED11
        case 11: GPIO=4;TRISIO=43;ANSEL=3;break; //LED12
    }
}   
